"""add indexes for common filter columns

Revision ID: 42974904923b
Revises: 421b64a46bb5
Create Date: 2026-08-18 13:08:19.706374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42974904923b'
down_revision: Union[str, Sequence[str], None] = '421b64a46bb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_reimbursement_requests_category'), 'reimbursement_requests', ['category'], unique=False)
    op.create_index(op.f('ix_reimbursement_requests_expense_date'), 'reimbursement_requests', ['expense_date'], unique=False)
    op.create_index(op.f('ix_reimbursement_requests_requester_id'), 'reimbursement_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_reimbursement_requests_reviewer_id'), 'reimbursement_requests', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_reimbursement_requests_status'), 'reimbursement_requests', ['status'], unique=False)
    op.create_index(op.f('ix_request_history_request_id'), 'request_history', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_history_request_id'), table_name='request_history')
    op.drop_index(op.f('ix_reimbursement_requests_status'), table_name='reimbursement_requests')
    op.drop_index(op.f('ix_reimbursement_requests_reviewer_id'), table_name='reimbursement_requests')
    op.drop_index(op.f('ix_reimbursement_requests_requester_id'), table_name='reimbursement_requests')
    op.drop_index(op.f('ix_reimbursement_requests_expense_date'), table_name='reimbursement_requests')
    op.drop_index(op.f('ix_reimbursement_requests_category'), table_name='reimbursement_requests')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    # ### end Alembic commands ###
